name: auto-create-milestone

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seunggabi/auto-create-milestone@v1.1.1
        id: run
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: d-
          days: Friday
          count: 4
          format: YYYY.MM.DD
