name: auto-close-milestone

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  auto-close-milestone:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: seunggabi/auto-close-milestone@v1.0.0
        id: run
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: result
        run: echo ${{ steps.run.outputs.milestones }}
