name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR: test

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: ./sh/install.sh
        working-directory: ${{ env.DIR }}
      - id: test
        run: |
          export PYTHONPATH=${PYTHONHOME}:../seunggabi_core_python:. && pytest */*.py
          status=$?
          echo "status=${status}" >> "$GITHUB_OUTPUT"
        working-directory: ${{ env.DIR }}
      - run: exit ${{ steps.test.outputs.status }}
